spring:
  profiles:
    active: support, security, system, basedata, weixin, iot, acs, oa, ss
  messages:
    basename: META-INF/support, META-INF/security, META-INF/system, META-INF/basedata, META-INF/weixin, META-INF/iot, META-INF/acs, META-INF/oa, META-INF/ss
# logging:
#   config: classpath:META-INF/log4j2.xml
pengsoft:
  system:
    captcha:
      verification-required-uris:
        - /api/user-details/reset-password
        - /api/user-details/bind
  security:
    uris-permitted:
      - /api/user-details/reset-password
      - /api/user-details/bind
      - /api/system/captcha/generate
      - /api/weixin/**
      - /api/iot/device/heartbeat
      - /api/acs/person-face-data/sync-page
      - /api/acs/person-face-data/sync-one
      - /api/acs/access-record/sync
    oauth2:
      authorization-server:
        enabled: true
        endpoint: http://localhost:8080
      resource-server:
        enabled: true
        endpoint: http://localhost:8080
      clients:
        - id: admin
          secret: d42c0ea4-cfcd-41ff-93a9-d444915da8d7
          access-token-validity-seconds: 2592000
          grant-types:
            - password
        - id: mp
          secret: 13639e6f-7b36-4852-aa88-d35f45430244
          access-token-validity-seconds: 2592000
          grant-types:
            - mp