pengsoft:
  system:
    messaging:
        sms:
          endpoint: ${SMS_ENDPOINT}
          access-key-id: ${SMS_ACCESS_KEY_ID}
          access-key-secret: ${SMS_ACCESS_KEY_SECRET}
    storage:
        enabled: true
        access-key-id: ${OSS_ACCESS_KEY_ID}
        access-key-secret: ${OSS_ACCESS_KEY_SECRET}
        public-bucket: ${OSS_PUBLIC_BUCKET_NAME}
        locked-bucket: ${OSS_LOCKED_BUCKET_NAME}
        public-bucket-endpoint: ${OSS_PUBLIC_BUCKET_ENDPOINT}
        locked-bucket-endpoint: ${OSS_LOCKED_BUCKET_ENDPOINT}
        public-access-path-prefix: ${OSS_PUBLIC_BUCKET_ACCESS_PATH_PREFIX}
        locked-access-path-prefix: ${OSS_LOCKED_BUCKET_ACCESS_PATH_PREFIX}