package com.pengsoft.system.repository;

import java.time.LocalDateTime;
import java.util.List;

import javax.persistence.QueryHint;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import com.pengsoft.security.domain.User;
import com.pengsoft.support.repository.EntityRepository;
import com.pengsoft.system.domain.Captcha;
import com.pengsoft.system.domain.QCaptcha;
import com.querydsl.core.types.dsl.DateTimePath;

import org.springframework.data.jpa.repository.QueryHints;
import org.springframework.data.querydsl.binding.QuerydslBindings;
import org.springframework.stereotype.Repository;

/**
 * The repository interface of {@link Captcha} based on JPA
 *
 * @author peng.dang@pengsoft.com
 * @since 1.0.0
 */
@Repository
public interface CaptchaRepository extends EntityRepository<QCaptcha, Captcha, String> {

    @Override
    default void customize(final QuerydslBindings bindings, final QCaptcha root) {
        EntityRepository.super.customize(bindings, root);
        bindings.bind(root.expiredAt).first(DateTimePath::before);
    }

    /**
     * Returns all entities generated by user, with type and after createdAt
     * 
     * @param userId    The id of {@link User}
     * @param createdAt The time of the captcha created at.
     */
    @QueryHints(value = @QueryHint(name = "org.hibernate.cacheable", value = "true"), forCounting = false)
    List<Captcha> findAllByUserIdAndCreatedAtAfterOrderByCreatedAtDesc(@NotBlank String userId,
            @NotNull LocalDateTime createdAt);

}
