pengsoft:
  weixin:
    miniapp:
      configs:
        - appid: ${WX_MINIAPP_1_APP_ID}
          secret: ${WX_MINIAPP_1_SECRET}
          token: ${WX_MINIAPP_1_TOKEN}
          aesKey: ${WX_MINIAPP_1_TAES_KEY}
          msgDataFormat: JSON