pengsoft:
  weixin:
    miniapp:
      configs:
        - appid: wx302f8ba7876e6006
          secret: d5c4416a770a81d65aab940e29e8b502
          token: weixin.pengsoft
          aesKey: L27zCe1If3tLg4ADMj7fg0V7zlOe6zQX4GPOyYcKuD7
          msgDataFormat: JSON